version: '3.8'

services:
  db:
    image: postgis/postgis
    container_name: flight-badges-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flightbadges
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  backend:
    build: ./backend
    container_name: flight-badges-backend
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/flightbadges

  frontend:
    build: ./frontend
    container_name: flight-badges-frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend